---
name: CI

on:
  push:
    branches: [main]
  pull_request:
  
env:
  FORCE_COLOR: "1" # make tools pretty.

jobs:
  generate-jobs:
    runs-on: ubuntu-latest
    outputs:
      python: ${{ steps.set-matrix.outputs.python }}
    steps:
    - uses: actions/checkout@v3
    - uses: wntrblm/nox@main
    - id: set-matrix
      shell: bash
      run: echo python=$(nox --json -l | jq -c '[.[].python]') | tee --append $GITHUB_OUTPUT
  tests:
    name: Tests on ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    needs: generate-jobs
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJson(needs.generate-jobs.outputs.python) }}
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: run nox.
        run: |
          pip install nox
          python -m nox --python ${{ matrix.python-version }} \
          -- sessions tests
  